import sanitizeHtml from 'sanitize-html';

const safeCssValue =
  /^(?!.*(?:url\s*\(|expression\s*\(|javascript:|@import))/iu;

const allowedTags = [
  'a',
  'abbr',
  'article',
  'b',
  'blockquote',
  'br',
  'caption',
  'cite',
  'code',
  'col',
  'colgroup',
  'dd',
  'del',
  'details',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'input',
  'kbd',
  'li',
  'mark',
  'math',
  'annotation',
  'menclose',
  'mfrac',
  'mi',
  'mn',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'ms',
  'mspace',
  'msqrt',
  'mstyle',
  'msub',
  'msubsup',
  'msup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
  'mrow',
  'semantics',
  'ol',
  'p',
  'pre',
  'q',
  'section',
  'small',
  'span',
  'strong',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'u',
  'ul',
  'var',
  'svg',
  'g',
  'defs',
  'marker',
  'path',
  'line',
  'polyline',
  'polygon',
  'rect',
  'circle',
  'ellipse',
  'text',
  'tspan',
  'title',
  'desc',
];

const commonAttributes = [
  'class',
  'id',
  'title',
  'role',
  'aria-label',
  'aria-hidden',
  'tabindex',
  'data-mermaid-id',
  'data-mermaid-source',
  'data-publication-math',
  'data-toc-id',
  'data-language',
  'style',
  'width',
  'height',
  'align',
  'colspan',
  'rowspan',
];

const allowedAttributes = {
  '*': commonAttributes,
  a: ['href', 'rel', 'target'],
  img: ['src', 'alt', 'width', 'height', 'loading'],
  input: ['type', 'checked', 'disabled'],
  svg: [
    'xmlns',
    'viewBox',
    'version',
    'fill',
    'stroke',
    'stroke-width',
    'width',
    'height',
    'preserveAspectRatio',
  ],
  g: [
    'transform',
    'fill',
    'stroke',
    'stroke-width',
    'fill-rule',
    'clip-rule',
    'opacity',
  ],
  path: [
    'd',
    'fill',
    'stroke',
    'stroke-width',
    'fill-rule',
    'clip-rule',
    'stroke-linecap',
    'stroke-linejoin',
    'stroke-dasharray',
    'marker-start',
    'marker-mid',
    'marker-end',
  ],
  line: [
    'x1',
    'x2',
    'y1',
    'y2',
    'stroke',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
    'marker-start',
    'marker-mid',
    'marker-end',
  ],
  polyline: [
    'points',
    'fill',
    'stroke',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
  ],
  polygon: ['points', 'fill', 'stroke', 'stroke-width'],
  rect: [
    'x',
    'y',
    'rx',
    'ry',
    'width',
    'height',
    'fill',
    'stroke',
    'stroke-width',
  ],
  circle: ['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width'],
  ellipse: ['cx', 'cy', 'rx', 'ry', 'fill', 'stroke', 'stroke-width'],
  text: [
    'x',
    'y',
    'dx',
    'dy',
    'text-anchor',
    'dominant-baseline',
    'transform',
    'fill',
    'font-size',
    'font-family',
  ],
  tspan: ['x', 'y', 'dx', 'dy', 'text-anchor', 'font-size'],
  marker: [
    'viewBox',
    'refX',
    'refY',
    'markerWidth',
    'markerHeight',
    'orient',
    'markerUnits',
  ],
  math: ['xmlns', 'display'],
  mstyle: ['displaystyle', 'scriptlevel'],
  annotation: ['encoding'],
};

function sanitizeFragment(html: string): string {
  const sanitized = sanitizeHtml(html, {
    allowedTags,
    allowedAttributes,
    allowedStyles: {
      '*': {
        color: [safeCssValue],
        background: [safeCssValue],
        'background-color': [safeCssValue],
        border: [safeCssValue],
        'border-color': [safeCssValue],
        'border-radius': [safeCssValue],
        display: [safeCssValue],
        fill: [safeCssValue],
        'font-family': [safeCssValue],
        'font-size': [safeCssValue],
        'font-style': [safeCssValue],
        'font-weight': [safeCssValue],
        'letter-spacing': [safeCssValue],
        height: [safeCssValue],
        'line-height': [safeCssValue],
        margin: [safeCssValue],
        'margin-bottom': [safeCssValue],
        'margin-left': [safeCssValue],
        'margin-right': [safeCssValue],
        'margin-top': [safeCssValue],
        'min-width': [safeCssValue],
        opacity: [safeCssValue],
        overflow: [safeCssValue],
        'overflow-wrap': [safeCssValue],
        padding: [safeCssValue],
        position: [safeCssValue],
        right: [safeCssValue],
        top: [safeCssValue],
        'stroke-width': [safeCssValue],
        'text-align': [safeCssValue],
        'text-anchor': [safeCssValue],
        'text-indent': [safeCssValue],
        transform: [safeCssValue],
        'transform-origin': [safeCssValue],
        'vertical-align': [safeCssValue],
        width: [safeCssValue],
        'white-space': [safeCssValue],
      },
    },
    allowedSchemes: ['http', 'https', 'mailto', 'data'],
    allowedSchemesByTag: {
      img: ['data'],
      a: ['http', 'https', 'mailto'],
    },
    allowedSchemesAppliedToAttributes: ['href', 'src', 'cite'],
    allowProtocolRelative: false,
    disallowedTagsMode: 'discard',
    parseStyleAttributes: true,
  });

  return sanitized;
}

function wasUnsafeContentRemoved(html: string, sanitized: string): boolean {
  const unsafeContentPattern =
    /<\s*(?:script|iframe|object|embed|foreignObject)\b|\bon[a-z]+\s*=|javascript\s*:|@import|(?:url|expression)\s*\(/iu;
  return sanitized !== html && unsafeContentPattern.test(html);
}

export function sanitizePublicationHtml(html: string): {
  html: string;
  removedContent: boolean;
} {
  const sanitized = sanitizeFragment(html);
  return {
    html: sanitized,
    removedContent: wasUnsafeContentRemoved(html, sanitized),
  };
}
